name: PHP CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1'] # https://www.php.net/supported-versions.php
    steps:
    - uses: actions/checkout@v3
    - name: Use PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl, intl, soap
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer update --prefer-dist --no-progress
    # - name: Run test suite
    #   run: composer run-script test

  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install --prefer-dist --no-progress
      - name: Configure PHPCS
        run: ./vendor/squizlabs/php_codesniffer/bin/phpcs --config-set ignore_warnings_on_exit 1
      - run: composer run-script cs-check
